#!/usr/bin/env bash
#
# Create a certificate and sign it with sub-CA
#

if [ $# -ne 2 ]; then
  echo "Usage: $0 <client|osd|common> foo.cnf"
  exit 1
fi

certName=$(basename $2 .cnf)
ca=$1

openssl req -new \
  -config $1 \
  -out certs/${certName}.csr \
  -nodes
openssl ca \
  -config etc/${ca}-ca.conf \
  -in certs/${certName}.csr \
  -out certs/${certName}.crt \
  -extensions server_ext
