#!/usr/bin/env bash
#
# Create a certificate and sign it with sub-CA
#

if [ $# -ne 1 ]; then
  echo "Usage: $0 foo.cnf"
  exit 1
fi

certName=$(basename $1 .cnf)

openssl req -new \
  -config $1 \
  -out certs/${certName}.csr \
  -nodes
openssl ca \
  -config etc/sub-ca.conf \
  -in certs/${certName}.csr \
  -out certs/${certName}.crt \
  -extensions server_ext
