#!/usr/bin/env bash
#
# Create a certificate and sign it with sub-CA
#

if [ $# -ne 1 ]; then
  echo "Usage: $0 foo.cnf"
  exit 1
fi

certName=$(basename $1 .cnf)

for ca in client dir mrc osd; do
  openssl req -new \
    -config $1 \
    -out certs/${ca}-${certName}.csr \
    -keyout certs/${ca}-${certName}.key \
    -nodes
  openssl ca \
    -config etc/${ca}-ca.conf \
    -in certs/${ca}-${certName}.csr \
    -out certs/${ca}-${certName}.crt \
    -extensions server_ext
done
