#!/bin/dash
# setup tahoe, start it if needed

# Once tahoe is OK, start other stuff
service tor start
service postgresql start
service spampd start
service postfix start
service dovecot start

# stupid while in order to keep it up
while true; do sleep 1; done
