#!/bin/dash
# setup tahoe, start it if needed

# Once tahoe is OK, start other stuff
service tahoe-lafs start
service cron start
service ssh start
service tor start
if [ -f /etc/init.d/postgresql ]; then
  service postgresql start
  service spampd start
  service postfix start
  service dovecot start
fi

echo
echo 'SYSTEM READY'
echo
echo 'Entering loop'
# stupid while in order to keep it up
while true; do sleep 1; done
echo 'GOODBYE'
