#!/bin/dash

echo 'clean up pre-generated keys for Tor HS'
rm -f /var/lib/tor/{mail,postgresql,tahoe,webmail}/*
service tor start

echo 'waiting a bit'
sleep 5

service tahoe-lafs start

echo 'Should mount Tahoe "filesystem" now'

service cron start
service ssh start

if [ -f /etc/init.d/postgresql ]; then
  service postgresql start
  service spampd start
  service postfix start
  service dovecot start
fi

echo
echo 'SYSTEM READY'
echo

if [ -d /var/lib/tahoe-lafs/introducer/private ]; then
  echo -n 'introducer furl: '
  cat /var/lib/tahoe-lafs/introducer/private/introducer.furl
  echo -n 'introducer log port: '
  cat /var/lib/tahoe-lafs/introducer/private/logport.furl
fi

echo 'Entering loop'
# stupid while in order to keep it up
while true; do sleep 1; done
echo 'GOODBYE'
